export interface AbroadAsset {
  ticker: string;
  name: string;
  sector: string;
  type: 'STOCK' | 'REIT' | 'ETF' | 'OTHER';
}

export const ABROAD_ASSETS: AbroadAsset[] = [
  { ticker: 'VOO', name: 'Vanguard S&P 500 ETF', sector: 'Índice EUA', type: 'ETF' },
  { ticker: 'IVV', name: 'iShares Core S&P 500 ETF', sector: 'Índice EUA', type: 'ETF' },
  { ticker: 'QQQ', name: 'Invesco QQQ Trust (Nasdaq 100)', sector: 'Tecnologia', type: 'ETF' },
  { ticker: 'VTI', name: 'Vanguard Total Stock Market ETF', sector: 'Índice EUA', type: 'ETF' },
  { ticker: 'VXUS', name: 'Vanguard Total International Stock ETF', sector: 'Global', type: 'ETF' },
  { ticker: 'SCHD', name: 'Schwab US Dividend Equity ETF', sector: 'Dividendos', type: 'ETF' },
  { ticker: 'VNQ', name: 'Vanguard Real Estate ETF', sector: 'Imobiliário', type: 'ETF' },
  { ticker: 'VYM', name: 'Vanguard High Dividend Yield ETF', sector: 'Dividendos', type: 'ETF' },
  { ticker: 'ARKK', name: 'ARK Innovation ETF', sector: 'Inovação', type: 'ETF' },
  { ticker: 'O', name: 'Realty Income Corp.', sector: 'Imobiliário', type: 'REIT' },
  { ticker: 'AMT', name: 'American Tower Corp.', sector: 'Imobiliário', type: 'REIT' },
  { ticker: 'PLD', name: 'Prologis Inc.', sector: 'Imobiliário', type: 'REIT' },
  { ticker: 'June 22, 2026', name: 'MRVL', sector: 'Marvell Technology', type: 'STOCK' },
  { ticker: 'June 1, 2026', name: 'FDXF', sector: 'FedEx Freight', type: 'STOCK' },
  { ticker: 'May 7, 2026', name: 'VEEV', sector: 'Veeva Systems', type: 'STOCK' },
  { ticker: 'April 9, 2026', name: 'CASY', sector: 'Casey\'s', type: 'STOCK' },
  { ticker: 'March 23, 2026', name: 'VRT', sector: 'Vertiv', type: 'STOCK' },
  { ticker: 'February 9, 2026', name: 'CIEN', sector: 'Ciena', type: 'STOCK' },
  { ticker: 'December 22, 2025', name: 'CRH', sector: 'CRH', type: 'STOCK' },
  { ticker: 'December 11, 2025', name: 'ARES', sector: 'Ares Management', type: 'STOCK' },
  { ticker: 'November 28, 2025', name: 'SNDK', sector: 'Sandisk', type: 'STOCK' },
  { ticker: 'November 3, 2025', name: 'Q', sector: 'Qnity Electronics', type: 'STOCK' },
  { ticker: 'October 30, 2025', name: 'SOLS', sector: 'Solstice Advanced Materials', type: 'STOCK' },
  { ticker: 'September 22, 2025', name: 'EME', sector: 'Emcor', type: 'STOCK' },
  { ticker: 'August 28, 2025', name: 'IBKR', sector: 'Interactive Brokers', type: 'STOCK' },
  { ticker: 'July 23, 2025', name: 'XYZ', sector: 'Block, Inc.', type: 'STOCK' },
  { ticker: 'July 18, 2025', name: 'TTD', sector: 'Trade Desk (The)', type: 'STOCK' },
  { ticker: 'July 9, 2025', name: 'DDOG', sector: 'Datadog', type: 'STOCK' },
  { ticker: 'May 19, 2025', name: 'COIN', sector: 'Coinbase', type: 'STOCK' },
  { ticker: 'March 24, 2025', name: 'DASH', sector: 'DoorDash', type: 'STOCK' },
  { ticker: 'December 23, 2024', name: 'APO', sector: 'Apollo Global Management', type: 'STOCK' },
  { ticker: 'November 26, 2024', name: 'TPL', sector: 'Texas Pacific Land Corporation', type: 'STOCK' },
  { ticker: 'September 30, 2024', name: 'AMTM', sector: 'Amentum', type: 'STOCK' },
  { ticker: 'September 23, 2024', name: 'PLTR', sector: 'Palantir Technologies', type: 'STOCK' },
  { ticker: 'June 24, 2024', name: 'KKR', sector: 'KKR', type: 'STOCK' },
  { ticker: 'May 8, 2024', name: 'VST', sector: 'Vistra', type: 'STOCK' },
  { ticker: 'April 2, 2024', name: 'GEV', sector: 'GE Vernova', type: 'STOCK' },
  { ticker: 'April 1, 2024', name: 'SOLV', sector: 'Solventum', type: 'STOCK' },
  { ticker: 'March 18, 2024', name: 'SMCI', sector: 'Supermicro', type: 'STOCK' },
  { ticker: 'December 18, 2023', name: 'UBER', sector: 'Uber', type: 'STOCK' },
  { ticker: 'October 18, 2023', name: 'HUBB', sector: 'Hubbell', type: 'STOCK' },
  { ticker: 'October 2, 2023', name: 'VLTO', sector: 'Veralto', type: 'STOCK' },
  { ticker: 'September 18, 2023', name: 'BX', sector: 'Blackstone', type: 'STOCK' },
  { ticker: 'August 25, 2023', name: 'KVUE', sector: 'Kenvue', type: 'STOCK' },
  { ticker: 'June 20, 2023', name: 'PANW', sector: 'Palo Alto Networks', type: 'STOCK' },
  { ticker: 'May 4, 2023', name: 'AXON', sector: 'Axon Enterprise', type: 'STOCK' },
  { ticker: 'March 20, 2023', name: 'FICO', sector: 'Fair Isaac', type: 'STOCK' },
  { ticker: 'March 15, 2023', name: 'BG', sector: 'Bunge Global', type: 'STOCK' },
  { ticker: 'January 4, 2023', name: 'GEHC', sector: 'GE HealthCare', type: 'STOCK' },
  { ticker: 'December 22, 2022', name: 'STLD', sector: 'Steel Dynamics', type: 'STOCK' },
  { ticker: 'December 19, 2022', name: 'FSLR', sector: 'First Solar', type: 'STOCK' },
  { ticker: 'December 15, 2022', name: 'MBC', sector: 'MasterBrand', type: 'STOCK' },
  { ticker: 'November 1, 2022', name: 'ACGL', sector: 'Arch Capital Group', type: 'STOCK' },
  { ticker: 'October 12, 2022', name: 'TRGP', sector: 'Targa Resources', type: 'STOCK' },
  { ticker: 'October 3, 2022', name: 'PCG', sector: 'PG&amp;E', type: 'STOCK' },
  { ticker: 'September 19, 2022', name: 'CSGP', sector: 'CoStar Group', type: 'STOCK' },
  { ticker: 'June 21, 2022', name: 'KDP', sector: 'Keurig Dr Pepper', type: 'STOCK' },
  { ticker: 'June 8, 2022', name: 'VICI', sector: 'Vici Properties', type: 'STOCK' },
  { ticker: 'April 11, 2022', name: 'WBD', sector: 'Warner Bros. Discovery', type: 'STOCK' },
  { ticker: 'April 4, 2022', name: 'CPT', sector: 'Camden Property Trust', type: 'STOCK' },
  { ticker: 'March 2, 2022', name: 'MOH', sector: 'Molina Healthcare', type: 'STOCK' },
  { ticker: 'February 15, 2022', name: 'NDSN', sector: 'Nordson Corporation', type: 'STOCK' },
  { ticker: 'February 2, 2022', name: 'CEG', sector: 'Constellation Energy', type: 'STOCK' },
  { ticker: 'December 20, 2021', name: 'SBNY', sector: 'Signature Bank', type: 'STOCK' },
  { ticker: 'December 14, 2021', name: 'EPAM', sector: 'EPAM Systems', type: 'STOCK' },
  { ticker: 'September 20, 2021', name: 'MTCH', sector: 'Match Group', type: 'STOCK' },
  { ticker: 'August 30, 2021', name: 'TECH', sector: 'Bio-Techne', type: 'STOCK' },
  { ticker: 'July 21, 2021', name: 'MRNA', sector: 'Moderna', type: 'STOCK' },
  { ticker: 'June 3, 2021', name: 'OGN', sector: 'Organon &amp; Co.', type: 'STOCK' },
  { ticker: 'May 14, 2021', name: 'CRL', sector: 'Charles River Laboratories', type: 'STOCK' },
  { ticker: 'April 20, 2021', name: 'PTC', sector: 'PTC', type: 'STOCK' },
  { ticker: 'March 22, 2021', name: 'NXPI', sector: 'NXP', type: 'STOCK' },
  { ticker: 'February 12, 2021', name: 'MPWR', sector: 'Monolithic Power Systems', type: 'STOCK' },
  { ticker: 'January 21, 2021', name: 'TRMB', sector: 'Trimble', type: 'STOCK' },
  { ticker: 'January 7, 2021', name: 'ENPH', sector: 'Enphase Energy', type: 'STOCK' },
  { ticker: 'December 21, 2020', name: 'TSLA', sector: 'Tesla', type: 'STOCK' },
  { ticker: 'October 9, 2020', name: 'VNT', sector: 'Vontier', type: 'STOCK' },
  { ticker: 'October 7, 2020', name: 'POOL', sector: 'Pool Corporation', type: 'STOCK' },
  { ticker: 'September 21, 2020', name: 'ETSY', sector: 'Etsy', type: 'STOCK' },
  { ticker: 'June 22, 2020', name: 'BIO', sector: 'Bio-Rad Laboratories', type: 'STOCK' },
  { ticker: 'May 22, 2020', name: 'WST', sector: 'West Pharmaceutical Services', type: 'STOCK' },
  { ticker: 'May 12, 2020', name: 'DPZ', sector: 'Domino\'s Pizza', type: 'STOCK' },
  { ticker: 'April 3, 2020', name: 'OTIS', sector: 'Otis Worldwide', type: 'STOCK' },
  { ticker: 'April 1, 2020', name: 'HWM', sector: 'Howmet Aerospace', type: 'STOCK' },
  { ticker: 'March 2, 2020', name: 'IR', sector: 'Ingersoll Rand', type: 'STOCK' },
  { ticker: 'January 28, 2020', name: 'PAYC', sector: 'Paycom', type: 'STOCK' },
  { ticker: 'December 23, 2019', name: 'LYV', sector: 'Live Nation Entertainment', type: 'STOCK' },
  { ticker: 'December 9, 2019', name: 'ODFL', sector: 'Old Dominion Freight Line', type: 'STOCK' },
  { ticker: 'December 5, 2019', name: 'WRB', sector: 'W. R. Berkley Corporation', type: 'STOCK' },
  { ticker: 'November 21, 2019', name: 'NOW', sector: 'ServiceNow', type: 'STOCK' },
  { ticker: 'October 3, 2019', name: 'LVS', sector: 'Las Vegas Sands', type: 'STOCK' },
  { ticker: 'September 26, 2019', name: 'NVR', sector: 'NVR', type: 'STOCK' },
  { ticker: 'September 23, 2019', name: 'CDW', sector: 'CDW Corporation', type: 'STOCK' },
  { ticker: 'August 9, 2019', name: 'LDOS', sector: 'Leidos', type: 'STOCK' },
  { ticker: 'July 15, 2019', name: 'TMUS', sector: 'T-Mobile US', type: 'STOCK' },
  { ticker: 'July 1, 2019', name: 'MKTX', sector: 'MarketAxess', type: 'STOCK' },
  { ticker: 'June 11, 2019', name: 'AMCR', sector: 'Amcor', type: 'STOCK' },
  { ticker: 'June 7, 2019', name: 'BMS', sector: 'Bemis', type: 'STOCK' },
  { ticker: 'June 3, 2019', name: 'DD', sector: 'DuPont', type: 'STOCK' },
  { ticker: 'April 2, 2019', name: 'DOW', sector: 'Dow', type: 'STOCK' },
  { ticker: 'March 19, 2019', name: 'FOXA', sector: 'Fox Corporation', type: 'STOCK' },
  { ticker: 'February 27, 2019', name: 'WAB', sector: 'Wabtec', type: 'STOCK' },
  { ticker: 'February 15, 2019', name: 'ATO', sector: 'Atmos Energy', type: 'STOCK' },
  { ticker: 'January 18, 2019', name: 'TFX', sector: 'Teleflex', type: 'STOCK' },
  { ticker: 'January 2, 2019', name: 'FRC', sector: 'First Republic Bank', type: 'STOCK' },
  { ticker: 'December 24, 2018', name: 'CE', sector: 'Celanese', type: 'STOCK' },
  { ticker: 'December 3, 2018', name: 'LW', sector: 'Lamb Weston', type: 'STOCK' },
  { ticker: 'November 13, 2018', name: 'JKHY', sector: 'Jack Henry &amp; Associates', type: 'STOCK' },
  { ticker: 'November 6, 2018', name: 'KEYS', sector: 'Keysight', type: 'STOCK' },
  { ticker: 'October 11, 2018', name: 'FTNT', sector: 'Fortinet', type: 'STOCK' },
  { ticker: 'October 1, 2018', name: 'ROL', sector: 'Rollins', type: 'STOCK' },
  { ticker: 'September 14, 2018', name: 'WCG', sector: 'WellCare', type: 'STOCK' },
  { ticker: 'August 28, 2018', name: 'ANET', sector: 'Arista Networks', type: 'STOCK' },
  { ticker: 'July 2, 2018', name: 'CPRT', sector: 'Copart', type: 'STOCK' },
  { ticker: 'June 20, 2018', name: 'FLT', sector: 'FleetCor Technologies', type: 'STOCK' },
  { ticker: 'June 18, 2018', name: 'BR', sector: 'Broadridge Financial Solutions', type: 'STOCK' },
  { ticker: 'June 7, 2018', name: 'TWTR', sector: 'Twitter', type: 'STOCK' },
  { ticker: 'June 5, 2018', name: 'EVRG', sector: 'Evergy', type: 'STOCK' },
  { ticker: 'May 31, 2018', name: 'ABMD', sector: 'Abiomed', type: 'STOCK' },
  { ticker: 'April 4, 2018', name: 'MSCI', sector: 'MSCI', type: 'STOCK' },
  { ticker: 'March 19, 2018', name: 'TTWO', sector: 'Take-Two Interactive', type: 'STOCK' },
  { ticker: 'March 7, 2018', name: 'IPGP', sector: 'IPG Photonics', type: 'STOCK' },
  { ticker: 'January 3, 2018', name: 'HII', sector: 'Huntington Ingalls Industries', type: 'STOCK' },
  { ticker: 'October 13, 2017', name: 'NCLH', sector: 'Norwegian Cruise Line Holdings', type: 'STOCK' },
  { ticker: 'September 18, 2017', name: 'CDNS', sector: 'Cadence Design Systems', type: 'STOCK' },
  { ticker: 'September 1, 2017', name: 'DWDP', sector: 'DuPont', type: 'STOCK' },
  { ticker: 'August 29, 2017', name: 'Q', sector: 'QuintilesIMS', type: 'STOCK' },
  { ticker: 'August 8, 2017', name: 'BHF', sector: 'Brighthouse Financial', type: 'STOCK' },
  { ticker: 'July 26, 2017', name: 'DRE', sector: 'Duke Realty Corp', type: 'STOCK' },
  { ticker: 'July 7, 2017', name: 'BKR', sector: 'Baker Hughes', type: 'STOCK' },
  { ticker: 'June 19, 2017', name: 'HLT', sector: 'Hilton', type: 'STOCK' },
  { ticker: 'June 2, 2017', name: 'INFO', sector: 'IHS Markit', type: 'STOCK' },
  { ticker: 'April 5, 2017', name: 'IT', sector: 'Gartner', type: 'STOCK' },
  { ticker: 'April 4, 2017', name: 'DXC', sector: 'DXC Technology', type: 'STOCK' },
  { ticker: 'March 20, 2017', name: 'AMD', sector: 'Advanced Micro Devices', type: 'STOCK' },
  { ticker: 'March 16, 2017', name: 'SNPS', sector: 'Synopsys', type: 'STOCK' },
  { ticker: 'March 13, 2017', name: 'DISH', sector: 'Dish Network', type: 'STOCK' },
  { ticker: 'March 2, 2017', name: 'REG', sector: 'Regency Centers', type: 'STOCK' },
  { ticker: 'March 1, 2017', name: 'CBOE', sector: 'Cboe Holdings', type: 'STOCK' },
  { ticker: 'February 28, 2017', name: 'INCY', sector: 'Incyte', type: 'STOCK' },
  { ticker: 'January 5, 2017', name: 'IDXX', sector: 'Idexx Laboratories', type: 'STOCK' },
  { ticker: 'December 2, 2016', name: 'MAA', sector: 'Mid-America Apartments', type: 'STOCK' },
  { ticker: 'November 1, 2016', name: 'ARNC', sector: 'Arconic', type: 'STOCK' },
  { ticker: 'September 30, 2016', name: 'COTY', sector: 'Coty', type: 'STOCK' },
  { ticker: 'September 22, 2016', name: 'COO', sector: 'The Cooper Companies', type: 'STOCK' },
  { ticker: 'September 8, 2016', name: 'CHTR', sector: 'Charter Communications', type: 'STOCK' },
  { ticker: 'September 6, 2016', name: 'MTD', sector: 'Mettler Toledo', type: 'STOCK' },
  { ticker: 'July 5, 2016', name: 'FTV', sector: 'Fortive Corp', type: 'STOCK' },
  { ticker: 'July 1, 2016', name: 'LNT', sector: 'Alliant Energy Corp', type: 'STOCK' },
  { ticker: 'June 22, 2016', name: 'FBHS', sector: 'Fortune Brands Home &amp; Security', type: 'STOCK' },
  { ticker: 'June 3, 2016', name: 'TDG', sector: 'TransDigm Group', type: 'STOCK' },
  { ticker: 'May 31, 2016', name: 'AJG', sector: 'Arthur J. Gallagher &amp; Co.', type: 'STOCK' },
  { ticker: 'May 23, 2016', name: 'LKQ', sector: 'LKQ Corporation', type: 'STOCK' },
  { ticker: 'May 18, 2016', name: 'DLR', sector: 'Digital Realty', type: 'STOCK' },
  { ticker: 'May 13, 2016', name: 'ALK', sector: 'Alaska Air Group', type: 'STOCK' },
  { ticker: 'May 3, 2016', name: 'AYI', sector: 'Acuity Brands', type: 'STOCK' },
  { ticker: 'April 25, 2016', name: 'GPN', sector: 'Global Payments', type: 'STOCK' },
  { ticker: 'April 18, 2016', name: 'ULTA', sector: 'Ulta Beauty', type: 'STOCK' },
  { ticker: 'April 8, 2016', name: 'UA', sector: 'Under Armour (Class C)', type: 'STOCK' },
  { ticker: 'April 4, 2016', name: 'FL', sector: 'Foot Locker', type: 'STOCK' },
  { ticker: 'March 30, 2016', name: 'HOLX', sector: 'Hologic', type: 'STOCK' },
  { ticker: 'March 7, 2016', name: 'UDR', sector: 'UDR', type: 'STOCK' },
  { ticker: 'March 4, 2016', name: 'AWK', sector: 'American Water Works', type: 'STOCK' },
  { ticker: 'February 22, 2016', name: 'CXO', sector: 'Concho Resources', type: 'STOCK' },
  { ticker: 'February 1, 2016', name: 'CFG', sector: 'Citizens', type: 'STOCK' },
  { ticker: 'January 19, 2016', name: 'EXR', sector: 'Extra Space Storage', type: 'STOCK' },
  { ticker: 'January 5, 2016', name: 'WLTW', sector: 'Willis Towers Watson', type: 'STOCK' },
  { ticker: 'December 29, 2015', name: 'CHD', sector: 'Church &amp; Dwight', type: 'STOCK' },
  { ticker: 'December 1, 2015', name: 'CSRA', sector: 'CSRA', type: 'STOCK' },
  { ticker: 'November 19, 2015', name: 'ILMN', sector: 'Illumina', type: 'STOCK' },
  { ticker: 'November 18, 2015', name: 'SYF', sector: 'Synchrony Financial', type: 'STOCK' },
  { ticker: 'November 2, 2015', name: 'HPE', sector: 'Hewlett Packard Enterprise', type: 'STOCK' },
  { ticker: 'October 7, 2015', name: 'VRSK', sector: 'Verisk Analytics', type: 'STOCK' },
  { ticker: 'September 18, 2015', name: 'CMCSK', sector: 'Comcast Class K Special', type: 'STOCK' },
  { ticker: 'September 2, 2015', name: 'UAL', sector: 'United Continental Holdings', type: 'STOCK' },
  { ticker: 'August 28, 2015', name: 'ATVI', sector: 'Activision Blizzard', type: 'STOCK' },
  { ticker: 'July 29, 2015', name: 'SIG', sector: 'Signet Jewelers', type: 'STOCK' },
  { ticker: 'July 20, 2015', name: 'PYPL', sector: 'PayPal', type: 'STOCK' },
  { ticker: 'July 8, 2015', name: 'AAP', sector: 'Advance Auto Parts', type: 'STOCK' },
  { ticker: 'July 6, 2015', name: 'KHC', sector: 'Kraft Heinz', type: 'STOCK' },
  { ticker: 'July 2, 2015', name: 'CPGX', sector: 'Columbia Pipeline Group', type: 'STOCK' },
  { ticker: 'July 1, 2015', name: 'JBHT', sector: 'J.B. Hunt', type: 'STOCK' },
  { ticker: 'June 11, 2015', name: 'QRVO', sector: 'Qorvo', type: 'STOCK' },
  { ticker: 'April 7, 2015', name: 'O', sector: 'Realty Income Corporation', type: 'STOCK' },
  { ticker: 'March 23, 2015', name: 'AAL', sector: 'American Airlines Group', type: 'STOCK' },
  { ticker: 'March 18, 2015', name: 'HSIC', sector: 'Henry Schein', type: 'STOCK' },
  { ticker: 'March 12, 2015', name: 'SWKS', sector: 'Skyworks', type: 'STOCK' },
  { ticker: 'January 27, 2015', name: 'HCA', sector: 'HCA Holdings', type: 'STOCK' },
  { ticker: 'December 5, 2014', name: 'RCL', sector: 'Royal Caribbean Cruises', type: 'STOCK' },
  { ticker: 'November 5, 2014', name: 'LVLT', sector: 'Level 3 Communications', type: 'STOCK' },
  { ticker: 'September 20, 2014', name: 'URI', sector: 'United Rentals', type: 'STOCK' },
  { ticker: 'August 18, 2014', name: 'MNK', sector: 'Mallinckrodt', type: 'STOCK' },
  { ticker: 'August 6, 2014', name: 'DISCK', sector: 'Discovery Communications', type: 'STOCK' },
  { ticker: 'July 2, 2014', name: 'MLM', sector: 'Martin Marietta', type: 'STOCK' },
  { ticker: 'July 1, 2014', name: 'AMG', sector: 'Affiliated Managers Group', type: 'STOCK' },
  { ticker: 'June 20, 2014', name: 'XEC', sector: 'Cimarex Energy', type: 'STOCK' },
  { ticker: 'May 8, 2014', name: 'AVGO', sector: 'Avago Technologies', type: 'STOCK' },
  { ticker: 'May 1, 2014', name: 'UA', sector: 'Under Armour', type: 'STOCK' },
  { ticker: 'April 3, 2014', name: 'GOOGL', sector: 'Google', type: 'STOCK' },
  { ticker: 'April 2, 2014', name: 'ESS', sector: 'Essex Property Trust', type: 'STOCK' },
  { ticker: 'March 21, 2014', name: 'GMCR', sector: 'Keurig Green Mountain', type: 'STOCK' },
  { ticker: 'January 24, 2014', name: 'TSCO', sector: 'Tractor Supply', type: 'STOCK' },
  { ticker: 'December 23, 2013', name: 'ADS', sector: 'Alliance Data Systems', type: 'STOCK' },
  { ticker: 'December 10, 2013', name: 'GGP', sector: 'General Growth Properties', type: 'STOCK' },
  { ticker: 'December 2, 2013', name: 'ALLE', sector: 'Allegion', type: 'STOCK' },
  { ticker: 'November 13, 2013', name: 'KORS', sector: 'Michael Kors', type: 'STOCK' },
  { ticker: 'October 29, 2013', name: 'RIG', sector: 'Transocean', type: 'STOCK' },
  { ticker: 'September 20, 2013', name: 'VRTX', sector: 'Vertex Pharmaceuticals', type: 'STOCK' },
  { ticker: 'September 10, 2013', name: 'DAL', sector: 'Delta Air Lines', type: 'STOCK' },
  { ticker: 'July 8, 2013', name: 'NLSN', sector: 'Nielsen Holdings', type: 'STOCK' },
  { ticker: 'July 1, 2013', name: 'NWSA', sector: '21st Century Fox', type: 'STOCK' },
  { ticker: 'June 21, 2013', name: 'ZTS', sector: 'Zoetis', type: 'STOCK' },
  { ticker: 'June 6, 2013', name: 'GM', sector: 'General Motors', type: 'STOCK' },
  { ticker: 'May 23, 2013', name: 'KSU', sector: 'Kansas City Southern', type: 'STOCK' },
  { ticker: 'May 8, 2013', name: 'MAC', sector: 'Macerich', type: 'STOCK' },
  { ticker: 'April 30, 2013', name: 'REGN', sector: 'Regeneron Pharmaceuticals', type: 'STOCK' },
  { ticker: 'February 15, 2013', name: 'PVH', sector: 'PVH', type: 'STOCK' },
  { ticker: 'January 2, 2013', name: 'ABBV', sector: 'AbbVie', type: 'STOCK' },
  { ticker: 'December 21, 2012', name: 'DLPH', sector: 'Delphi Automotive', type: 'STOCK' },
  { ticker: 'December 11, 2012', name: 'GRMN', sector: 'Garmin', type: 'STOCK' },
  { ticker: 'December 3, 2012', name: 'DG', sector: 'Dollar General', type: 'STOCK' },
  { ticker: 'October 10, 2012', name: 'PETM', sector: 'PetSmart', type: 'STOCK' },
  { ticker: 'October 2, 2012', name: 'KRFT', sector: 'Kraft Foods', type: 'STOCK' },
  { ticker: 'October 1, 2012', name: 'ADT', sector: 'ADT', type: 'STOCK' },
  { ticker: 'September 5, 2012', name: 'LYB', sector: 'LyondellBasell', type: 'STOCK' },
  { ticker: 'July 31, 2012', name: 'ESV', sector: 'Ensco', type: 'STOCK' },
  { ticker: 'July 2, 2012', name: 'STX', sector: 'Seagate Technology', type: 'STOCK' },
  { ticker: 'June 29, 2012', name: 'MNST', sector: 'Monster Beverage', type: 'STOCK' },
  { ticker: 'June 5, 2012', name: 'LRCX', sector: 'Lam Research', type: 'STOCK' },
  { ticker: 'May 21, 2012', name: 'ALXN', sector: 'Alexion Pharmaceuticals', type: 'STOCK' },
  { ticker: 'May 17, 2012', name: 'KMI', sector: 'Kinder Morgan', type: 'STOCK' },
  { ticker: 'April 23, 2012', name: 'PSX', sector: 'Phillips 66', type: 'STOCK' },
  { ticker: 'April 3, 2012', name: 'FOSL', sector: 'Fossil', type: 'STOCK' },
  { ticker: 'March 13, 2012', name: 'CCI', sector: 'Crown Castle', type: 'STOCK' },
  { ticker: 'December 31, 2011', name: 'WPX', sector: 'WPX Energy', type: 'STOCK' },
  { ticker: 'December 20, 2011', name: 'TRIP', sector: 'TripAdvisor', type: 'STOCK' },
  { ticker: 'December 16, 2011', name: 'BWA', sector: 'BorgWarner', type: 'STOCK' },
  { ticker: 'December 12, 2011', name: 'GAS', sector: 'AGL Resources.', type: 'STOCK' },
  { ticker: 'November 18, 2011', name: 'CBE', sector: 'Cooper Industries', type: 'STOCK' },
  { ticker: 'October 31, 2011', name: 'XYL', sector: 'Xylem', type: 'STOCK' },
  { ticker: 'October 14, 2011', name: 'TEL', sector: 'TE Connectivity', type: 'STOCK' },
  { ticker: 'September 23, 2011', name: 'MOS', sector: 'The Mosaic Company', type: 'STOCK' },
  { ticker: 'July 5, 2011', name: 'ACN', sector: 'Accenture', type: 'STOCK' },
  { ticker: 'June 30, 2011', name: 'MPC', sector: 'Marathon Oil', type: 'STOCK' },
  { ticker: 'June 1, 2011', name: 'ANR', sector: 'Alpha Natural Resources', type: 'STOCK' },
  { ticker: 'April 27, 2011', name: 'CMG', sector: 'Chipotle Mexican Grill', type: 'STOCK' },
  { ticker: 'April 1, 2011', name: 'BLK', sector: 'BlackRock', type: 'STOCK' },
  { ticker: 'March 31, 2011', name: 'EW', sector: 'Edwards Lifesciences', type: 'STOCK' },
  { ticker: 'February 28, 2011', name: 'COV', sector: 'Covidien', type: 'STOCK' },
  { ticker: 'February 25, 2011', name: 'JOYG', sector: 'Joy Global', type: 'STOCK' },
  { ticker: 'January 3, 2011', name: 'MMI', sector: 'Motorola Mobility', type: 'STOCK' },
  { ticker: 'December 17, 2010', name: 'CVC', sector: 'Cablevision', type: 'STOCK' },
  { ticker: 'November 17, 2010', name: 'IR', sector: 'Ingersoll-Rand', type: 'STOCK' },
  { ticker: 'August 26, 2010', name: 'TYC', sector: 'Tyco International', type: 'STOCK' },
  { ticker: 'July 14, 2010', name: 'CB', sector: 'Chubb', type: 'STOCK' },
  { ticker: 'June 30, 2010', name: 'QEP', sector: 'QEP Resources', type: 'STOCK' },
  { ticker: 'June 28, 2010', name: 'KMX', sector: 'CarMax', type: 'STOCK' },
  { ticker: 'April 29, 2010', name: 'CERN', sector: 'Cerner', type: 'STOCK' },
  { ticker: 'February 26, 2010', name: 'HP', sector: 'Helmerich &amp; Payne', type: 'STOCK' },
  { ticker: 'December 18, 2009', name: 'V', sector: 'Visa', type: 'STOCK' },
  { ticker: 'November 3, 2009', name: 'PCLN', sector: 'Priceline.com', type: 'STOCK' },
  { ticker: 'September 28, 2009', name: 'ARG', sector: 'Airgas', type: 'STOCK' },
  { ticker: 'August 19, 2009', name: 'FMC', sector: 'FMC Corporation', type: 'STOCK' },
  { ticker: 'June 29, 2009', name: 'PCS', sector: 'MetroPCS', type: 'STOCK' },
  { ticker: 'June 5, 2009', name: 'FTI', sector: 'FMC Technologies', type: 'STOCK' },
  { ticker: 'March 3, 2009', name: 'HRL', sector: 'Hormel Foods', type: 'STOCK' },
  { ticker: 'December 31, 2008', name: 'OI', sector: 'Owens-Illinois', type: 'STOCK' },
  { ticker: 'September 16, 2008', name: 'HRS', sector: 'Harris Corporation', type: 'STOCK' },
  { ticker: 'September 12, 2008', name: 'CRM', sector: 'Salesforce', type: 'STOCK' },
  { ticker: 'July 1, 2008', name: 'AKS', sector: 'AK Steel', type: 'STOCK' },
  { ticker: 'June 23, 2008', name: 'COG', sector: 'Cabot Oil &amp; Gas', type: 'STOCK' },
  { ticker: 'June 10, 2008', name: 'LO', sector: 'Lorillard Tobacco Company', type: 'STOCK' },
  { ticker: 'December 20, 2007', name: 'RRC', sector: 'Range Resources', type: 'STOCK' },
  { ticker: 'December 13, 2007', name: 'GME', sector: 'GameStop', type: 'STOCK' },
  { ticker: 'October 26, 2007', name: 'JEC', sector: 'Jacobs Engineering Group', type: 'STOCK' },
  { ticker: 'October 2, 2007', name: 'EXPE', sector: 'Expedia', type: 'STOCK' },
  { ticker: 'October 1, 2007', name: 'TDC', sector: 'Teradata', type: 'STOCK' },
  { ticker: 'September 27, 2007', name: 'TSO', sector: 'Tesoro Corporation', type: 'STOCK' },
  { ticker: 'September 26, 2007', name: 'ICE', sector: 'Intercontinental Exchange', type: 'STOCK' },
  { ticker: 'August 24, 2007', name: 'LUK', sector: 'Leucadia National', type: 'STOCK' },
  { ticker: 'July 2, 2007', name: 'DFS', sector: 'Discover Financial', type: 'STOCK' },
  { ticker: 'March 30, 2007', name: 'KFT', sector: 'Kraft Foods', type: 'STOCK' },
  { ticker: 'January 10, 2007', name: 'AVB', sector: 'AvalonBay Communities', type: 'STOCK' },
  { ticker: 'June 2, 2006', name: 'JNPR', sector: 'Juniper Networks', type: 'STOCK' },
  { ticker: 'November 18, 2005', name: 'AMZN', sector: 'Amazon', type: 'STOCK' },
  { ticker: 'July 1, 2005', name: 'STZ', sector: 'Constellation Brands', type: 'STOCK' },
  { ticker: 'September 25, 2003', name: 'ESRX', sector: 'Express Scripts', type: 'STOCK' },
  { ticker: 'December 5, 2000', name: 'INTU', sector: 'Intuit', type: 'STOCK' },
  { ticker: 'July 27, 2000', name: 'JDSU', sector: 'JDS Uniphase', type: 'STOCK' },
  { ticker: 'June 12, 2000', name: 'CVG', sector: 'Convergys', type: 'STOCK' },
  { ticker: 'June 7, 2000', name: 'SBUX', sector: 'Starbucks', type: 'STOCK' },
  { ticker: 'December 8, 1999', name: 'YHOO', sector: 'Yahoo!', type: 'STOCK' },
  { ticker: 'June 9, 1999', name: 'WLP', sector: 'Wellpoint', type: 'STOCK' },
  { ticker: 'April 12, 1999', name: 'ACT', sector: 'Actavis', type: 'STOCK' },
  { ticker: 'December 11, 1998', name: 'FSR', sector: 'Firstar', type: 'STOCK' },
  { ticker: 'June 17, 1997', name: 'CCR', sector: 'Countrywide Credit Industries', type: 'STOCK' },
  { ticker: 'September 30, 1994', name: 'NCC', sector: 'National City', type: 'STOCK' },
  { ticker: 'July 1, 1976', name: 'BUD', sector: 'Anheuser Busch', type: 'STOCK' },
];

export const classifyAbroadAsset = (ticker: string): { type: 'STOCK' | 'REIT' | 'ETF' | 'OTHER', sector: string } => {
  const t = ticker.toUpperCase().trim();
  
  const found = ABROAD_ASSETS.find(s => s.ticker === t);
  if (found) return { type: found.type, sector: found.sector };

  if (t.length > 0 && t.length <= 4) {
    return { type: 'STOCK', sector: 'Outros' };
  }

  return { type: 'OTHER', sector: 'Outros' };
};

export const searchAbroadAssets = (query: string): AbroadAsset[] => {
  if (!query || query.length < 1) return [];
  const q = query.toUpperCase().trim();
  
  const results = ABROAD_ASSETS.filter(
    s => s.ticker.startsWith(q) || s.name.toUpperCase().includes(q)
  );

  if (results.length === 0 && q.length >= 1) {
    const classification = classifyAbroadAsset(q);
    if (classification.type !== 'OTHER') {
      return [{
        ticker: q,
        name: `Ativo detectado: ${q}`,
        sector: classification.sector,
        type: classification.type as any
      }];
    }
  }

  return results.slice(0, 8);
};
