export interface FinancialQuote {
  day: number;
  quote: string;
  author: string;
}

export const financialQuotes: FinancialQuote[] = [
  { day: 1, quote: "Não poupe o que sobra depois de gastar, gaste o que sobra depois de poupar.", author: "Warren Buffett" },
  { day: 2, quote: "O preço é o que você paga. O valor é o que você recebe.", author: "Warren Buffett" },
  { day: 3, quote: "Risco vem de não saber o que você está fazendo.", author: "Warren Buffett" },
  { day: 4, quote: "Alguém está sentado na sombra hoje porque alguém plantou uma árvore há muito tempo.", author: "Warren Buffett" },
  { day: 5, quote: "Nunca dependa de uma única fonte de renda. Invista para criar uma segunda fonte.", author: "Warren Buffett" },
  { day: 6, quote: "Os ricos adquirem ativos. Os pobres e a classe média adquirem passivos que pensam ser ativos.", author: "Robert Kiyosaki" },
  { day: 7, quote: "A educação financeira é a base da riqueza.", author: "Robert Kiyosaki" },
  { day: 8, quote: "Não trabalhe pelo dinheiro, faça o dinheiro trabalhar para você.", author: "Robert Kiyosaki" },
  { day: 9, quote: "O medo de perder dinheiro é real. Todos o têm. Até os ricos. Mas não é ter medo que é o problema. É como você lida com o medo.", author: "Robert Kiyosaki" },
  { day: 10, quote: "Um investimento em conhecimento paga os melhores juros.", author: "Benjamin Franklin" },
  { day: 11, quote: "Cuide dos centavos e os reais cuidarão de si mesmos.", author: "Benjamin Franklin" },
  { day: 12, quote: "Quem compra o que não precisa, vende o que precisa.", author: "Benjamin Franklin" },
  { day: 13, quote: "O tempo é dinheiro.", author: "Benjamin Franklin" },
  { day: 14, quote: "Saiba o que você possui e saiba por que você o possui.", author: "Peter Lynch" },
  { day: 15, quote: "O investidor individual tem uma grande vantagem sobre os profissionais.", author: "Peter Lynch" },
  { day: 16, quote: "Você ganha dinheiro em ações não ficando assustado com elas.", author: "Peter Lynch" },
  { day: 17, quote: "Invista no que você conhece.", author: "Peter Lynch" },
  { day: 18, quote: "Quem vive de ilusões morre de desilusões.", author: "Ray Dalio" },
  { day: 19, quote: "A dor mais a reflexão é igual ao progresso.", author: "Ray Dalio" },
  { day: 20, quote: "Não confunda o que você deseja ser verdade com o que realmente é verdade.", author: "Ray Dalio" },
  { day: 21, quote: "A diversificação é a única refeição grátis em investimentos.", author: "Ray Dalio" },
  { day: 22, quote: "A grande maioria das pessoas que ficam ricas o fazem lentamente.", author: "Charlie Munger" },
  { day: 23, quote: "Gaste cada dia tentando ser um pouco mais sábio do que quando você acordou.", author: "Charlie Munger" },
  { day: 24, quote: "A melhor coisa que um ser humano pode fazer é ajudar outro ser humano a saber mais.", author: "Charlie Munger" },
  { day: 25, quote: "Inverta, sempre inverta.", author: "Charlie Munger" },
  { day: 26, quote: "Não tente cronometrar o mercado.", author: "John Bogle" },
  { day: 27, quote: "O tempo é seu amigo, o impulso é seu inimigo.", author: "John Bogle" },
  { day: 28, quote: "Mantenha os custos baixos e fique no curso.", author: "John Bogle" },
  { day: 29, quote: "A simplicidade é a chave mestra da sabedoria financeira.", author: "John Bogle" },
  { day: 30, quote: "Viva como ninguém vive hoje para viver como ninguém vive amanhã.", author: "Dave Ramsey" },
  { day: 31, quote: "Um orçamento é dizer ao seu dinheiro para onde ir, em vez de se perguntar para onde ele foi.", author: "Dave Ramsey" },
  { day: 32, quote: "Você deve ganhar o controle sobre o seu dinheiro ou a falta dele controlará você para sempre.", author: "Dave Ramsey" },
  { day: 33, quote: "Aja como se o seu dinheiro fosse importante, porque é.", author: "Dave Ramsey" },
  { day: 34, quote: "O segredo da riqueza é simples: encontre uma maneira de fazer mais por outros do que qualquer outra pessoa.", author: "Tony Robbins" },
  { day: 35, quote: "Não é sobre ter recursos, é sobre ser engenhoso.", author: "Tony Robbins" },
  { day: 36, quote: "A única coisa que o impede de obter o que você quer é a história que você continua contando a si mesmo.", author: "Tony Robbins" },
  { day: 37, quote: "Onde o foco vai, a energia flui.", author: "Tony Robbins" },
  { day: 38, quote: "O ponto de partida de toda conquista é o desejo.", author: "Napoleon Hill" },
  { day: 39, quote: "Não espere. O tempo nunca será perfeito.", author: "Napoleon Hill" },
  { day: 40, quote: "A força da mente é a única limitação.", author: "Napoleon Hill" },
  { day: 41, quote: "O que a mente pode conceber e acreditar, ela pode alcançar.", author: "Napoleon Hill" },
  { day: 42, quote: "A melhor hora para plantar uma árvore foi há 20 anos. A segunda melhor hora é agora.", author: "Provérbio Chinês" },
  { day: 43, quote: "Não conte os dias, faça os dias contarem.", author: "Muhammad Ali" },
  { day: 44, quote: "O sucesso é a soma de pequenos esforços repetidos dia após dia.", author: "Robert Collier" },
  { day: 45, quote: "A disciplina é a ponte entre metas e realizações.", author: "Jim Rohn" },
  { day: 46, quote: "Você não pode mudar o vento, mas pode ajustar as velas.", author: "Provérbio" },
  { day: 47, quote: "A fortuna favorece os audazes.", author: "Virgílio" },
  { day: 48, quote: "O dinheiro é um bom servo, mas um mau mestre.", author: "Francis Bacon" },
  { day: 49, quote: "A riqueza consiste não em ter grandes posses, mas em ter poucas necessidades.", author: "Epicteto" },
  { day: 50, quote: "Não é o quanto você ganha, mas o quanto você guarda que importa.", author: "Provérbio" },
  { day: 51, quote: "A paciência é amarga, mas seus frutos são doces.", author: "Aristóteles" },
  { day: 52, quote: "O homem que move uma montanha começa carregando pequenas pedras.", author: "Confúcio" },
  { day: 53, quote: "A oportunidade dança com aqueles que já estão na pista.", author: "H. Jackson Brown Jr." },
  { day: 54, quote: "O maior risco é não correr nenhum risco.", author: "Mark Zuckerberg" },
  { day: 55, quote: "Sua rede é seu patrimônio líquido.", author: "Porter Gale" },
  { day: 56, quote: "O dinheiro não compra felicidade, mas é mais confortável chorar em um Mercedes do que em uma bicicleta.", author: "Provérbio" },
  { day: 57, quote: "A economia é a arte de fazer o máximo da vida.", author: "George Bernard Shaw" },
  { day: 58, quote: "Ganhar dinheiro é uma arte, trabalhar é uma arte e bons negócios são a melhor arte.", author: "Andy Warhol" },
  { day: 59, quote: "O dinheiro é apenas uma ferramenta. Ele o levará aonde você desejar, mas não o substituirá como motorista.", author: "Ayn Rand" },
  { day: 60, quote: "A riqueza não é sobre ter muito dinheiro; é sobre ter muitas opções.", author: "Chris Rock" },
  { day: 61, quote: "O investimento mais importante que você pode fazer é em si mesmo.", author: "Warren Buffett" },
  { day: 62, quote: "Nunca teste a profundidade do rio com os dois pés.", author: "Warren Buffett" },
  { day: 63, quote: "Seja ganancioso quando os outros estão com medo e tenha medo quando os outros estão gananciosos.", author: "Warren Buffett" },
  { day: 64, quote: "É melhor ter um desempenho aproximadamente certo do que precisamente errado.", author: "Warren Buffett" },
  { day: 65, quote: "Leva 20 anos para construir uma reputação e cinco minutos para arruiná-la.", author: "Warren Buffett" },
  { day: 66, quote: "Os vencedores não têm medo de perder. Mas os perdedores têm. O fracasso faz parte do processo de sucesso.", author: "Robert Kiyosaki" },
  { day: 67, quote: "A inteligência resolve problemas e produz dinheiro. O dinheiro sem inteligência financeira é dinheiro que logo desaparece.", author: "Robert Kiyosaki" },
  { day: 68, quote: "Seu futuro é criado pelo que você faz hoje, não amanhã.", author: "Robert Kiyosaki" },
  { day: 69, quote: "As pessoas bem-sucedidas fazem perguntas. Elas buscam novos professores. Estão sempre aprendendo.", author: "Robert Kiyosaki" },
  { day: 70, quote: "A maior parte das pessoas nunca fica rica simplesmente porque não foi treinada financeiramente para reconhecer oportunidades.", author: "Robert Kiyosaki" },
  { day: 71, quote: "Dívidas são como qualquer outra armadilha, fáceis o suficiente de entrar, mas difíceis o suficiente de sair.", author: "Henry Wheeler Shaw" },
  { day: 72, quote: "Economizar é uma boa coisa. Especialmente quando seus pais fizeram isso por você.", author: "Winston Churchill" },
  { day: 73, quote: "A felicidade não está em ter muito dinheiro, mas em ter mais do que o vizinho.", author: "Provérbio" },
  { day: 74, quote: "O dinheiro fala, mas não diz quando vai embora.", author: "Provérbio" },
  { day: 75, quote: "Compre quando todos estão vendendo e mantenha até que todos estejam comprando.", author: "J. Paul Getty" },
  { day: 76, quote: "A fórmula para o sucesso? Levante-se cedo, trabalhe duro, encontre petróleo.", author: "J. Paul Getty" },
  { day: 77, quote: "O dinheiro é como um braço ou uma perna - use-o ou perca-o.", author: "Henry Ford" },
  { day: 78, quote: "Não é o empregador quem paga os salários. Os empregadores apenas lidam com o dinheiro. É o cliente quem paga os salários.", author: "Henry Ford" },
  { day: 79, quote: "A riqueza é a capacidade de experimentar plenamente a vida.", author: "Henry David Thoreau" },
  { day: 80, quote: "Dinheiro é um terrível mestre, mas um excelente servo.", author: "P.T. Barnum" },
  { day: 81, quote: "O caminho para a riqueza depende de apenas duas palavras: trabalho e economia.", author: "Benjamin Franklin" },
  { day: 82, quote: "Lembre-se de que o crédito é dinheiro.", author: "Benjamin Franklin" },
  { day: 83, quote: "Aquele que entende os juros, ganha. Aquele que não entende, paga.", author: "Albert Einstein" },
  { day: 84, quote: "Os juros compostos são a oitava maravilha do mundo.", author: "Albert Einstein" },
  { day: 85, quote: "Tente não se tornar uma pessoa de sucesso, mas sim uma pessoa de valor.", author: "Albert Einstein" },
  { day: 86, quote: "A imaginação é mais importante que o conhecimento.", author: "Albert Einstein" },
  { day: 87, quote: "Você não precisa ser um cientista de foguetes. Investir não é um jogo onde o cara com QI 160 vence o cara com QI 130.", author: "Warren Buffett" },
  { day: 88, quote: "Chains of habit are too light to be felt until they are too heavy to be broken.", author: "Warren Buffett" },
  { day: 89, quote: "A volatilidade é longe de ser sinônimo de risco.", author: "Warren Buffett" },
  { day: 90, quote: "Nosso trabalho favorito de retenção é para sempre.", author: "Warren Buffett" },
  { day: 91, quote: "Só quando a maré baixa você descobre quem estava nadando nu.", author: "Warren Buffett" },
  { day: 92, quote: "O mercado de ações é um dispositivo para transferir dinheiro do impaciente para o paciente.", author: "Warren Buffett" },
  { day: 93, quote: "Não é necessário fazer coisas extraordinárias para obter resultados extraordinários.", author: "Warren Buffett" },
  { day: 94, quote: "A diferença entre pessoas bem-sucedidas e pessoas realmente bem-sucedidas é que pessoas realmente bem-sucedidas dizem não para quase tudo.", author: "Warren Buffett" },
  { day: 95, quote: "Honestidade é um presente muito caro. Não espere isso de pessoas baratas.", author: "Warren Buffett" },
  { day: 96, quote: "Se você não encontrar uma maneira de ganhar dinheiro enquanto dorme, trabalhará até morrer.", author: "Warren Buffett" },
  { day: 97, quote: "Compre apenas algo que você ficaria perfeitamente feliz em manter se o mercado fechasse por 10 anos.", author: "Warren Buffett" },
  { day: 98, quote: "A coisa mais importante a fazer se você se encontrar em um buraco é parar de cavar.", author: "Warren Buffett" },
  { day: 99, quote: "Leva-se uma vida inteira para construir uma reputação e cinco minutos para arruiná-la.", author: "Warren Buffett" },
  { day: 100, quote: "Quanto mais você aprende, mais você ganha.", author: "Warren Buffett" },
  { day: 101, quote: "A chave para ganhar dinheiro em ações é não ter medo delas.", author: "Peter Lynch" },
  { day: 102, quote: "Todos têm inteligência suficiente para ganhar dinheiro em ações. Nem todos têm estômago.", author: "Peter Lynch" },
  { day: 103, quote: "Atrás de cada ação há uma empresa. Descubra o que ela está fazendo.", author: "Peter Lynch" },
  { day: 104, quote: "Nunca invista em uma ideia que você não pode ilustrar com um lápis de cera.", author: "Peter Lynch" },
  { day: 105, quote: "O verdadeiro dinheiro em investimentos terá que ser feito não saindo e entrando, mas esperando.", author: "Charlie Munger" },
  { day: 106, quote: "Adquira sabedoria mundana e ajuste-a conforme o mundo muda.", author: "Charlie Munger" },
  { day: 107, quote: "Pegue uma ideia simples e leve-a a sério.", author: "Charlie Munger" },
  { day: 108, quote: "A melhor armadura de todas é manter-se fora do alcance do tiro.", author: "Charlie Munger" },
  { day: 109, quote: "Você precisa manter a mente aberta, mas não tão aberta que seu cérebro caia.", author: "Charlie Munger" },
  { day: 110, quote: "Não confunda brilhantismo com um mercado em alta.", author: "Charlie Munger" },
  { day: 111, quote: "O grande inimigo do investidor é ele mesmo.", author: "Benjamin Graham" },
  { day: 112, quote: "O investidor inteligente é um realista que vende para otimistas e compra de pessimistas.", author: "Benjamin Graham" },
  { day: 113, quote: "No curto prazo, o mercado é uma máquina de votação, mas no longo prazo é uma máquina de pesagem.", author: "Benjamin Graham" },
  { day: 114, quote: "A margem de segurança é sempre dependente do preço pago.", author: "Benjamin Graham" },
  { day: 115, quote: "As operações de investimento são aquelas que, após análise completa, prometem segurança do principal e retorno adequado.", author: "Benjamin Graham" },
  { day: 116, quote: "Não se preocupe com o que o mercado vai fazer. Você não tem controle sobre isso. Preocupe-se com o que você vai fazer se o mercado fizer isso ou aquilo.", author: "Ray Dalio" },
  { day: 117, quote: "Ele que vive por cristal, morrerá por cristal.", author: "Ray Dalio" },
  { day: 118, quote: "Radical transparência e meritocracia de ideias podem ser desconfortáveis no início.", author: "Ray Dalio" },
  { day: 119, quote: "Medite. Eu não posso superestimar o quanto isso me ajudou.", author: "Ray Dalio" },
  { day: 120, quote: "Faça suas paixões e seu trabalho serem a mesma coisa e você nunca terá que trabalhar.", author: "Ray Dalio" },
  { day: 121, quote: "A vida é como um jogo de pôquer. Você tem que jogar a mão que lhe foi dada.", author: "Ray Dalio" },
  { day: 122, quote: "Não deixe que o medo de perder seja maior que a emoção de ganhar.", author: "Robert Kiyosaki" },
  { day: 123, quote: "A palavra 'aposentadoria' não está no vocabulário dos ricos.", author: "Robert Kiyosaki" },
  { day: 124, quote: "Empregos são soluções de curto prazo para problemas de longo prazo.", author: "Robert Kiyosaki" },
  { day: 125, quote: "A principal razão pela qual as pessoas lutam financeiramente é porque passaram anos na escola, mas não aprenderam nada sobre dinheiro.", author: "Robert Kiyosaki" },
  { day: 126, quote: "Quanto mais você busca segurança, menos você tem.", author: "Robert Kiyosaki" },
  { day: 127, quote: "A educação é mais valiosa que o dinheiro, no longo prazo.", author: "Robert Kiyosaki" },
  { day: 128, quote: "Vencedores não são pessoas que nunca falham, mas pessoas que nunca desistem.", author: "Robert Kiyosaki" },
  { day: 129, quote: "O tamanho do seu sucesso é medido pela força do seu desejo.", author: "Robert Kiyosaki" },
  { day: 130, quote: "Dinheiro sem inteligência financeira desaparece rapidamente.", author: "Robert Kiyosaki" },
  { day: 131, quote: "Não economize o que sobra depois de gastar; gaste o que sobra depois de economizar.", author: "Warren Buffett" },
  { day: 132, quote: "Alguém está sentado à sombra hoje porque alguém plantou uma árvore há muito tempo atrás.", author: "Warren Buffett" },
  { day: 133, quote: "Você não pode fazer um bom negócio com uma pessoa ruim.", author: "Warren Buffett" },
  { day: 134, quote: "É muito melhor comprar uma empresa maravilhosa a um preço justo do que uma empresa justa a um preço maravilhoso.", author: "Warren Buffett" },
  { day: 135, quote: "Tempo é o amigo de negócios maravilhosos, o inimigo do medíocre.", author: "Warren Buffett" },
  { day: 136, quote: "Diversificação é proteção contra ignorância. Faz pouco sentido se você sabe o que está fazendo.", author: "Warren Buffett" },
  { day: 137, quote: "Eu sempre soube que seria rico. Acho que nunca duvidei disso por um minuto.", author: "Warren Buffett" },
  { day: 138, quote: "Seja você mesmo; todos os outros já foram escolhidos.", author: "Warren Buffett" },
  { day: 139, quote: "Aprenda a dizer não à maioria das coisas.", author: "Warren Buffett" },
  { day: 140, quote: "A melhor chance de implantar capital é quando as coisas estão caindo aos pedaços.", author: "Warren Buffett" },
  { day: 141, quote: "Viva dentro de suas possibilidades e economize para investir. Aprenda sobre investimentos.", author: "Dave Ramsey" },
  { day: 142, quote: "Mudança é dolorosa. Mas nada é tão doloroso quanto ficar preso em algum lugar que você não pertence.", author: "Dave Ramsey" },
  { day: 143, quote: "Você deve dizer ao seu dinheiro o que fazer ou ele desaparecerá.", author: "Dave Ramsey" },
  { day: 144, quote: "Adultos criam planos e seguem-nos. Crianças fazem o que parece bom.", author: "Dave Ramsey" },
  { day: 145, quote: "Ganhar dinheiro é comum. Ter disciplina financeira é raro.", author: "Dave Ramsey" },
  { day: 146, quote: "Não compre coisas que você não pode pagar, com dinheiro que você não tem, para impressionar pessoas que você não gosta.", author: "Dave Ramsey" },
  { day: 147, quote: "Você não pode sair de dívidas enquanto mantém tudo o que o colocou lá.", author: "Dave Ramsey" },
  { day: 148, quote: "Riqueza não é uma questão de inteligência, é uma questão de comportamento.", author: "Dave Ramsey" },
  { day: 149, quote: "Ninguém jamais alcançou grandeza financeira em um emprego de salário. Grandeza financeira vem de possuir coisas.", author: "Dave Ramsey" },
  { day: 150, quote: "Trabalhe como se não precisasse do dinheiro. Ame como se nunca tivesse sido magoado. Dance como se ninguém estivesse olhando.", author: "Dave Ramsey" },
  { day: 151, quote: "O sucesso deixa pistas.", author: "Tony Robbins" },
  { day: 152, quote: "Estabeleça metas que sejam grandes o suficiente para inspirá-lo e específicas o suficiente para serem alcançáveis.", author: "Tony Robbins" },
  { day: 153, quote: "A qualidade de sua vida é a qualidade de suas perguntas.", author: "Tony Robbins" },
  { day: 154, quote: "É em seus momentos de decisão que seu destino é moldado.", author: "Tony Robbins" },
  { day: 155, quote: "Se você faz o que sempre fez, obterá o que sempre obteve.", author: "Tony Robbins" },
  { day: 156, quote: "A única coisa impossível é aquilo que você não tenta.", author: "Tony Robbins" },
  { day: 157, quote: "Identifique seus problemas, mas dê seu poder e energia às soluções.", author: "Tony Robbins" },
  { day: 158, quote: "Sucesso é fazer o que você quer, quando quer, onde quer, com quem quer, o quanto quiser.", author: "Tony Robbins" },
  { day: 159, quote: "A vida é uma dádiva, e ela oferece o privilégio, oportunidade e responsabilidade de dar algo de volta.", author: "Tony Robbins" },
  { day: 160, quote: "Não é o que fazemos de vez em quando que molda nossas vidas. É o que fazemos consistentemente.", author: "Tony Robbins" },
  { day: 161, quote: "Desejo é o ponto de partida de toda realização.", author: "Napoleon Hill" },
  { day: 162, quote: "Pense e enriqueça.", author: "Napoleon Hill" },
  { day: 163, quote: "A persistência é para o caráter do homem o que o carbono é para o aço.", author: "Napoleon Hill" },
  { day: 164, quote: "Toda adversidade, todo fracasso, toda dor de cabeça carrega consigo a semente de um benefício igual ou maior.", author: "Napoleon Hill" },
  { day: 165, quote: "Você está onde está e o que é por causa de si mesmo.", author: "Napoleon Hill" },
  { day: 166, quote: "Não há limitações para a mente, exceto aquelas que reconhecemos.", author: "Napoleon Hill" },
  { day: 167, quote: "Esforço apenas libera totalmente sua recompensa após uma pessoa se recusar a desistir.", author: "Napoleon Hill" },
  { day: 168, quote: "Antes do sucesso vem em qualquer vida de homem, ele certamente encontrará derrota temporária e, talvez, algum fracasso.", author: "Napoleon Hill" },
  { day: 169, quote: "Você tem um cérebro e uma mente própria. Use-os e chegue às suas próprias decisões.", author: "Napoleon Hill" },
  { day: 170, quote: "A força e o crescimento vêm apenas através de esforço e luta contínuos.", author: "Napoleon Hill" },
  { day: 171, quote: "Não invista em fundos de investimento de alto custo.", author: "John Bogle" },
  { day: 172, quote: "Compre certo e mantenha.", author: "John Bogle" },
  { day: 173, quote: "O investidor individual deveria agir consistentemente como um investidor e não como um especulador.", author: "John Bogle" },
  { day: 174, quote: "Não procure a agulha no palheiro. Apenas compre o palheiro!", author: "John Bogle" },
  { day: 175, quote: "Tempo é seu amigo; impulso é seu inimigo.", author: "John Bogle" },
  { day: 176, quote: "Se você tem problemas imaginando uma perda de 20% em seu portfólio, você não deveria estar em ações.", author: "John Bogle" },
  { day: 177, quote: "A simplicidade é a chave mestra da sabedoria financeira.", author: "John Bogle" },
  { day: 178, quote: "Fique no curso. Não importa o que aconteça, fique no curso.", author: "John Bogle" },
  { day: 179, quote: "O mercado de ações é um gigante dispositivo de distração.", author: "John Bogle" },
  { day: 180, quote: "Custos importam. Então, minimize-os.", author: "John Bogle" },
  { day: 181, quote: "A riqueza é a habilidade de experimentar plenamente a vida.", author: "Henry David Thoreau" },
  { day: 182, quote: "Um homem é rico na proporção do número de coisas que ele pode deixar em paz.", author: "Henry David Thoreau" },
  { day: 183, quote: "Não gaste seu tempo ganhando a vida de tal forma que você não possa viver.", author: "Henry David Thoreau" },
  { day: 184, quote: "A riqueza é como água do mar; quanto mais bebemos, mais sede temos.", author: "Arthur Schopenhauer" },
  { day: 185, quote: "Dinheiro nunca fez um homem feliz ainda, nem fará. Quanto mais um homem tem, mais ele quer.", author: "Benjamin Franklin" },
  { day: 186, quote: "Beware of little expenses. A small leak will sink a great ship.", author: "Benjamin Franklin" },
  { day: 187, quote: "Quem vai ao leito sem jantar, levanta-se sem dívidas.", author: "Benjamin Franklin" },
  { day: 188, quote: "Compre o que você não precisa e logo venderá o que você precisa.", author: "Benjamin Franklin" },
  { day: 189, quote: "Lembre-se que tempo é dinheiro.", author: "Benjamin Franklin" },
  { day: 190, quote: "Um tostão economizado é um tostão ganho.", author: "Benjamin Franklin" },
  { day: 191, quote: "Aquele que multiplica riquezas multiplica preocupações.", author: "Benjamin Franklin" },
  { day: 192, quote: "Se você conhece como gastar menos do que ganha, você tem a pedra filosofal.", author: "Benjamin Franklin" },
  { day: 193, quote: "Dinheiro nunca fez um homem feliz ainda, nem fará. Não há nada na sua natureza para produzir felicidade.", author: "Benjamin Franklin" },
  { day: 194, quote: "Ele que espera viver de esperança morrerá de fome.", author: "Benjamin Franklin" },
  { day: 195, quote: "A preguiça viaja tão devagar que a pobreza logo a alcança.", author: "Benjamin Franklin" },
  { day: 196, quote: "Energia e persistência conquistam todas as coisas.", author: "Benjamin Franklin" },
  { day: 197, quote: "Sem dor, sem ganho.", author: "Benjamin Franklin" },
  { day: 198, quote: "Deus ajuda aqueles que se ajudam.", author: "Benjamin Franklin" },
  { day: 199, quote: "Nunca deixe para amanhã o que você pode fazer hoje.", author: "Benjamin Franklin" },
  { day: 200, quote: "Bem feito é melhor que bem dito.", author: "Benjamin Franklin" },
  { day: 201, quote: "O sucesso geralmente vem para aqueles que estão ocupados demais para procurá-lo.", author: "Henry David Thoreau" },
  { day: 202, quote: "Oportunidades não acontecem. Você as cria.", author: "Chris Grosser" },
  { day: 203, quote: "Não tenha medo de desistir do bom para ir para o ótimo.", author: "John D. Rockefeller" },
  { day: 204, quote: "Eu sempre tentei transformar cada desastre em uma oportunidade.", author: "John D. Rockefeller" },
  { day: 205, quote: "Se o seu único objetivo é se tornar rico, você nunca o alcançará.", author: "John D. Rockefeller" },
  { day: 206, quote: "A maneira de ganhar dinheiro é comprar quando o sangue está correndo nas ruas.", author: "John D. Rockefeller" },
  { day: 207, quote: "Não trabalhe por dinheiro; faça com que o dinheiro trabalhe para você.", author: "Robert Kiyosaki" },
  { day: 208, quote: "A pessoa mais perigosa no mundo é aquela que ouve, pensa e observa.", author: "Bruce Lee" },
  { day: 209, quote: "Conhecimento não é poder. Conhecimento é apenas potencial. Ação é poder.", author: "Tony Robbins" },
  { day: 210, quote: "A única maneira de fazer um ótimo trabalho é amar o que você faz.", author: "Steve Jobs" },
  { day: 211, quote: "Inovação distingue um líder de um seguidor.", author: "Steve Jobs" },
  { day: 212, quote: "Seu tempo é limitado, então não o desperdice vivendo a vida de outra pessoa.", author: "Steve Jobs" },
  { day: 213, quote: "Às vezes, quando você inova, comete erros. É melhor admiti-los rapidamente e continuar melhorando suas outras inovações.", author: "Steve Jobs" },
  { day: 214, quote: "Não deixe o barulho das opiniões dos outros abafar sua própria voz interior.", author: "Steve Jobs" },
  { day: 215, quote: "Fique com fome, fique tolo.", author: "Steve Jobs" },
  { day: 216, quote: "Qualidade é mais importante que quantidade. Um home run é muito melhor que dois doubles.", author: "Steve Jobs" },
  { day: 217, quote: "Design não é apenas como parece e como se sente. Design é como funciona.", author: "Steve Jobs" },
  { day: 218, quote: "Seja um padrão de qualidade. Algumas pessoas não estão acostumadas a um ambiente onde a excelência é esperada.", author: "Steve Jobs" },
  { day: 219, quote: "As pessoas que são loucas o suficiente para pensar que podem mudar o mundo são as que o fazem.", author: "Steve Jobs" },
  { day: 220, quote: "Não se preocupe com o fracasso; você só precisa estar certo uma vez.", author: "Drew Houston" },
  { day: 221, quote: "A melhor vingança é um sucesso massivo.", author: "Frank Sinatra" },
  { day: 222, quote: "Eu não falhei. Apenas encontrei 10.000 maneiras que não funcionam.", author: "Thomas Edison" },
  { day: 223, quote: "Muitos dos fracassos da vida são pessoas que não perceberam o quão perto estavam do sucesso quando desistiram.", author: "Thomas Edison" },
  { day: 224, quote: "Oportunidade é perdida pela maioria das pessoas porque está vestida de macacão e parece trabalho.", author: "Thomas Edison" },
  { day: 225, quote: "Gênio é um por cento de inspiração e noventa e nove por cento de transpiração.", author: "Thomas Edison" },
  { day: 226, quote: "Há uma maneira de fazer melhor - encontre-a.", author: "Thomas Edison" },
  { day: 227, quote: "Nunca desista de algo que você não pode passar um dia sem pensar.", author: "Winston Churchill" },
  { day: 228, quote: "Sucesso não é final, fracasso não é fatal: é a coragem de continuar que conta.", author: "Winston Churchill" },
  { day: 229, quote: "Atitude é uma pequena coisa que faz uma grande diferença.", author: "Winston Churchill" },
  { day: 230, quote: "O pessimista vê dificuldade em cada oportunidade. O otimista vê oportunidade em cada dificuldade.", author: "Winston Churchill" },
  { day: 231, quote: "Você nunca alcançará seu destino se parar e atirar pedras em cada cachorro que late.", author: "Winston Churchill" },
  { day: 232, quote: "O preço da grandeza é a responsabilidade.", author: "Winston Churchill" },
  { day: 233, quote: "Coragem é o que é preciso para se levantar e falar; coragem também é o que é preciso para sentar e ouvir.", author: "Winston Churchill" },
  { day: 234, quote: "Nós ganhamos a vida com o que recebemos, mas fazemos uma vida com o que damos.", author: "Winston Churchill" },
  { day: 235, quote: "O sucesso consiste em ir de fracasso em fracasso sem perda de entusiasmo.", author: "Winston Churchill" },
  { day: 236, quote: "Nunca, nunca, nunca desista.", author: "Winston Churchill" },
  { day: 237, quote: "A única coisa pior que começar algo e falhar é não começar nada.", author: "Seth Godin" },
  { day: 238, quote: "Em vez de se perguntar quando suas próximas férias são, talvez você devesse configurar uma vida que você não precisa escapar.", author: "Seth Godin" },
  { day: 239, quote: "Não encontre clientes para seus produtos, encontre produtos para seus clientes.", author: "Seth Godin" },
  { day: 240, quote: "Marketing não é mais sobre as coisas que você faz, mas sobre as histórias que você conta.", author: "Seth Godin" },
  { day: 241, quote: "Você não precisa de um novo plano para o próximo ano. Você precisa de um compromisso.", author: "Seth Godin" },
  { day: 242, quote: "A única maneira de vencer é aprender mais rápido que qualquer outra pessoa.", author: "Eric Ries" },
  { day: 243, quote: "Visão sem execução é alucinação.", author: "Thomas Edison" },
  { day: 244, quote: "O empreendedor sempre procura mudança, responde a ela e a explora como uma oportunidade.", author: "Peter Drucker" },
  { day: 245, quote: "A melhor maneira de prever o futuro é criá-lo.", author: "Peter Drucker" },
  { day: 246, quote: "Eficiência é fazer as coisas certas; eficácia é fazer as coisas certas.", author: "Peter Drucker" },
  { day: 247, quote: "O que é medido é gerenciado.", author: "Peter Drucker" },
  { day: 248, quote: "Conhecimento tem que ser melhorado, desafiado e aumentado constantemente, ou desaparece.", author: "Peter Drucker" },
  { day: 249, quote: "Os planos são inúteis, mas o planejamento é indispensável.", author: "Dwight D. Eisenhower" },
  { day: 250, quote: "A motivação é o que te faz começar. O hábito é o que te mantém.", author: "Jim Ryun" },
  { day: 251, quote: "Você não precisa ser grande para começar, mas precisa começar para ser grande.", author: "Zig Ziglar" },
  { day: 252, quote: "Pessoas não planejam falhar, elas falham em planejar.", author: "Zig Ziglar" },
  { day: 253, quote: "Você nasceu para vencer, mas para ser um vencedor, você deve planejar vencer, se preparar para vencer e esperar vencer.", author: "Zig Ziglar" },
  { day: 254, quote: "Não é o que você tem, é o que você faz com o que você tem que faz a diferença.", author: "Zig Ziglar" },
  { day: 255, quote: "Seu atitude, não sua aptidão, determinará sua altitude.", author: "Zig Ziglar" },
  { day: 256, quote: "Você pode ter tudo na vida que você quer se você apenas ajudar outras pessoas suficientes a conseguir o que elas querem.", author: "Zig Ziglar" },
  { day: 257, quote: "Lembre-se que o fracasso é um evento, não uma pessoa.", author: "Zig Ziglar" },
  { day: 258, quote: "A falta de direção, não a falta de tempo, é o problema. Todos nós temos dias de vinte e quatro horas.", author: "Zig Ziglar" },
  { day: 259, quote: "Você foi projetado para a realização, engenheirado para o sucesso e dotado com as sementes da grandeza.", author: "Zig Ziglar" },
  { day: 260, quote: "Não espere; o tempo nunca será 'perfeito'.", author: "Napoleon Hill" },
  { day: 261, quote: "A riqueza da mente pode ser a única riqueza verdadeira.", author: "Provérbio" },
  { day: 262, quote: "Invista em si mesmo. Seu eu é o único ativo que você realmente controla.", author: "Provérbio" },
  { day: 263, quote: "O melhor investimento que você pode fazer é em você mesmo.", author: "Warren Buffett" },
  { day: 264, quote: "Construa seu próprio sonho, ou alguém o contratará para construir o dele.", author: "Farrah Gray" },
  { day: 265, quote: "O dinheiro é um ótimo servo, mas um mestre terrível.", author: "Francis Bacon" },
  { day: 266, quote: "Riqueza consiste não em ter grandes posses, mas em ter poucas necessidades.", author: "Epicteto" },
  { day: 267, quote: "Não é o homem que tem muito pouco, mas o homem que deseja mais, que é pobre.", author: "Sêneca" },
  { day: 268, quote: "A felicidade não é na mera posse de dinheiro; está na alegria da conquista.", author: "Franklin D. Roosevelt" },
  { day: 269, quote: "Dinheiro é apenas uma ferramenta. Ele o levará aonde você deseja, mas não o substituirá como motorista.", author: "Ayn Rand" },
  { day: 270, quote: "Riqueza é a capacidade de experimentar plenamente a vida.", author: "Henry David Thoreau" },
  { day: 271, quote: "Não é sobre quanto dinheiro você ganha, mas quanto dinheiro você mantém.", author: "Robert Kiyosaki" },
  { day: 272, quote: "A pessoa que não sabe para onde está indo geralmente acaba em outro lugar.", author: "Laurence J. Peter" },
  { day: 273, quote: "Você deve esperar grandes coisas de si mesmo antes de poder fazê-las.", author: "Michael Jordan" },
  { day: 274, quote: "Eu falhei repetidamente na minha vida. E é por isso que eu tenho sucesso.", author: "Michael Jordan" },
  { day: 275, quote: "Talento vence jogos, mas trabalho em equipe e inteligência vencem campeonatos.", author: "Michael Jordan" },
  { day: 276, quote: "Alguns querem que aconteça, alguns desejam que aconteça, outros fazem acontecer.", author: "Michael Jordan" },
  { day: 277, quote: "Eu posso aceitar o fracasso, todos falham em algo. Mas eu não posso aceitar não tentar.", author: "Michael Jordan" },
  { day: 278, quote: "Obstáculos não têm que pará-lo. Se você encontrar uma parede, não vire e desista.", author: "Michael Jordan" },
  { day: 279, quote: "Sempre transforme uma situação negativa em uma positiva.", author: "Michael Jordan" },
  { day: 280, quote: "Se você está tentando alcançar, há sempre uma chance de que você possa falhar.", author: "Michael Jordan" },
  { day: 281, quote: "Meus heróis são e foram meus pais. Não posso ver ter alguém melhor como meus heróis.", author: "Michael Jordan" },
  { day: 282, quote: "Eu jogo para vencer, seja durante práticas ou um jogo real.", author: "Michael Jordan" },
  { day: 283, quote: "A única estratégia que é garantida para falhar é não correr riscos.", author: "Mark Zuckerberg" },
  { day: 284, quote: "Ideias não vêm totalmente formadas. Elas só se tornam claras à medida que você trabalha nelas.", author: "Mark Zuckerberg" },
  { day: 285, quote: "Mova-se rápido e quebre coisas. A menos que você esteja quebrando coisas, você não está se movendo rápido o suficiente.", author: "Mark Zuckerberg" },
  { day: 286, quote: "O maior risco é não correr nenhum risco.", author: "Mark Zuckerberg" },
  { day: 287, quote: "Eu acho que um erro simples que muitas empresas cometem é que elas trabalham muito para fazer o produto perfeito.", author: "Mark Zuckerberg" },
  { day: 288, quote: "Dê às pessoas o poder de compartilhar e tornar o mundo mais aberto e conectado.", author: "Mark Zuckerberg" },
  { day: 289, quote: "A questão que eu faço a mim mesmo quase todos os dias é: 'Estou fazendo a coisa mais importante que eu poderia estar fazendo?'", author: "Mark Zuckerberg" },
  { day: 290, quote: "Encontre aquela coisa que você é apaixonado. Se você não ama o que está fazendo, não faça.", author: "Mark Zuckerberg" },
  { day: 291, quote: "Pessoas influentes simplesmente fazem coisas.", author: "Mark Zuckerberg" },
  { day: 292, quote: "Meu objetivo nunca foi apenas criar uma empresa. Muitas pessoas interpretam mal isso, como se eu não me importasse com receita ou lucro.", author: "Mark Zuckerberg" },
  { day: 293, quote: "Sua marca é o que outras pessoas dizem sobre você quando você não está na sala.", author: "Jeff Bezos" },
  { day: 294, quote: "Se você duplicar o número de experimentos que você faz por ano, você vai duplicar sua inventividade.", author: "Jeff Bezos" },
  { day: 295, quote: "Nós vemos nossos clientes como convidados para uma festa, e nós somos os anfitriões.", author: "Jeff Bezos" },
  { day: 296, quote: "Eu sabia que se eu falhasse, eu não me arrependeria, mas eu sabia que a única coisa que eu poderia me arrepender era não tentar.", author: "Jeff Bezos" },
  { day: 297, quote: "Seja teimoso em visão, mas flexível em detalhes.", author: "Jeff Bezos" },
  { day: 298, quote: "O que é perigoso não é evoluir.", author: "Jeff Bezos" },
  { day: 299, quote: "Nós não fazemos dinheiro quando vendemos coisas. Fazemos dinheiro quando ajudamos os clientes a tomar decisões de compra.", author: "Jeff Bezos" },
  { day: 300, quote: "A coisa mais importante é estar focado no cliente. Nosso objetivo é ser a empresa mais centrada no cliente da Terra.", author: "Jeff Bezos" },
  { day: 301, quote: "A vida é muito curta para construir algo que ninguém quer.", author: "Ash Maurya" },
  { day: 302, quote: "Faça cada detalhe perfeito e limite o número de detalhes para aperfeiçoar.", author: "Jack Dorsey" },
  { day: 303, quote: "Torne-se a pessoa que merece as coisas que você quer.", author: "James Clear" },
  { day: 304, quote: "Você não sobe ao nível de suas metas. Você cai ao nível de seus sistemas.", author: "James Clear" },
  { day: 305, quote: "Cada ação que você toma é um voto para o tipo de pessoa que você deseja se tornar.", author: "James Clear" },
  { day: 306, quote: "Hábitos são os juros compostos da auto-melhoria.", author: "James Clear" },
  { day: 307, quote: "O objetivo não é ler um livro, o objetivo é se tornar um leitor.", author: "James Clear" },
  { day: 308, quote: "Mudança de comportamento é mudança de identidade.", author: "James Clear" },
  { day: 309, quote: "Você precisa amar o processo mais do que o evento.", author: "James Clear" },
  { day: 310, quote: "Sucesso é a soma de pequenos esforços repetidos dia após dia.", author: "Robert Collier" },
  { day: 311, quote: "A única pessoa que você está destinado a se tornar é a pessoa que você decide ser.", author: "Ralph Waldo Emerson" },
  { day: 312, quote: "Vá com confiança na direção de seus sonhos. Viva a vida que você imaginou.", author: "Henry David Thoreau" },
  { day: 313, quote: "Acredite que você pode e você já está no meio do caminho.", author: "Theodore Roosevelt" },
  { day: 314, quote: "Tudo o que você sempre quis está do outro lado do medo.", author: "George Addair" },
  { day: 315, quote: "Sonhe grande e ouse falhar.", author: "Norman Vaughan" },
  { day: 316, quote: "Desafios são o que torna a vida interessante e superá-los é o que torna a vida significativa.", author: "Joshua J. Marine" },
  { day: 317, quote: "Se você quer levantar-se, levante outra pessoa.", author: "Booker T. Washington" },
  { day: 318, quote: "Eu aprendi que as pessoas vão esquecer o que você disse, as pessoas vão esquecer o que você fez, mas as pessoas nunca vão esquecer como você as fez sentir.", author: "Maya Angelou" },
  { day: 319, quote: "Ou você administra o dia, ou o dia administra você.", author: "Jim Rohn" },
  { day: 320, quote: "Seja você mesmo; todos os outros já estão ocupados.", author: "Oscar Wilde" },
  { day: 321, quote: "Duas estradas divergiram em uma floresta, e eu - eu peguei a menos percorrida, e isso fez toda a diferença.", author: "Robert Frost" },
  { day: 322, quote: "Eu atribuo meu sucesso a isto: nunca dei ou aceitei uma desculpa.", author: "Florence Nightingale" },
  { day: 323, quote: "Você perde 100% dos tiros que você não dá.", author: "Wayne Gretzky" },
  { day: 324, quote: "Eu sozinho não posso mudar o mundo, mas posso jogar uma pedra nas águas para criar muitas ondulações.", author: "Madre Teresa" },
  { day: 325, quote: "Lembre-se de que não conseguir o que você quer às vezes é um golpe maravilhoso de sorte.", author: "Dalai Lama" },
  { day: 326, quote: "Você pode ser apenas uma pessoa para o mundo, mas para uma pessoa você pode ser o mundo.", author: "Dr. Seuss" },
  { day: 327, quote: "Acredite que você pode e você já está no meio do caminho.", author: "Theodore Roosevelt" },
  { day: 328, quote: "Não é o que você olha que importa, é o que você vê.", author: "Henry David Thoreau" },
  { day: 329, quote: "A mente é tudo. O que você pensa, você se torna.", author: "Buda" },
  { day: 330, quote: "A melhor época para plantar uma árvore foi há 20 anos. A segunda melhor época é agora.", author: "Provérbio Chinês" },
  { day: 331, quote: "Um empreendedor não é aquele que tem uma ideia. Um empreendedor é aquele que faz acontecer.", author: "Guy Kawasaki" },
  { day: 332, quote: "Não se preocupe com o fracasso; você só precisa estar certo uma vez.", author: "Drew Houston" },
  { day: 333, quote: "Mantenha seus olhos nas estrelas e seus pés no chão.", author: "Theodore Roosevelt" },
  { day: 334, quote: "Ensine-se a trabalhar duro quando ninguém está olhando.", author: "Provérbio" },
  { day: 335, quote: "O sucesso não é a chave para a felicidade. A felicidade é a chave para o sucesso.", author: "Albert Schweitzer" },
  { day: 336, quote: "Não conte os dias, faça os dias contarem.", author: "Muhammad Ali" },
  { day: 337, quote: "A única maneira impossível de fazer algo é não tentar.", author: "Provérbio" },
  { day: 338, quote: "Grandes coisas nunca vêm de zonas de conforto.", author: "Provérbio" },
  { day: 339, quote: "Sonhe maior. Faça maior.", author: "Provérbio" },
  { day: 340, quote: "Não pare quando estiver cansado. Pare quando terminar.", author: "Provérbio" },
  { day: 341, quote: "Acorde com determinação. Vá para a cama com satisfação.", author: "Provérbio" },
  { day: 342, quote: "Faça algo hoje que seu eu futuro agradecerá.", author: "Provérbio" },
  { day: 343, quote: "Pequeno progresso ainda é progresso.", author: "Provérbio" },
  { day: 344, quote: "Acredite em si mesmo e tudo será possível.", author: "Provérbio" },
  { day: 345, quote: "Seu limite é apenas sua imaginação.", author: "Provérbio" },
  { day: 346, quote: "Grandes coisas levam tempo.", author: "Provérbio" },
  { day: 347, quote: "Sonhe sem medo. Ame sem limites.", author: "Provérbio" },
  { day: 348, quote: "Seja mais forte que suas desculpas.", author: "Provérbio" },
  { day: 349, quote: "Não deseje por isso. Trabalhe por isso.", author: "Provérbio" },
  { day: 350, quote: "O sucesso não vem de apenas um dia. Vem de todos os dias.", author: "Provérbio" },
  { day: 351, quote: "Você é mais forte do que pensa.", author: "Provérbio" },
  { day: 352, quote: "Faça hoje valer a pena.", author: "Provérbio" },
  { day: 353, quote: "Seja a energia que você quer atrair.", author: "Provérbio" },
  { day: 354, quote: "Crie sua própria oportunidade.", author: "Provérbio" },
  { day: 355, quote: "Trabalhe duro em silêncio. Deixe o sucesso fazer o barulho.", author: "Provérbio" },
  { day: 356, quote: "A consistência é a chave do sucesso.", author: "Provérbio" },
  { day: 357, quote: "Não espere pela oportunidade. Crie-a.", author: "George Bernard Shaw" },
  { day: 358, quote: "O fracasso é o condimento que dá sabor ao sucesso.", author: "Truman Capote" },
  { day: 359, quote: "A ação é a chave fundamental para todo sucesso.", author: "Pablo Picasso" },
  { day: 360, quote: "Você é o que você faz, não o que você diz que vai fazer.", author: "Carl Jung" },
  { day: 361, quote: "A vida é 10% o que acontece com você e 90% como você reage a isso.", author: "Charles R. Swindoll" },
  { day: 362, quote: "Mudança é a lei da vida. E aqueles que olham apenas para o passado ou presente certamente perderão o futuro.", author: "John F. Kennedy" },
  { day: 363, quote: "Perfeição não é alcançável, mas se perseguirmos a perfeição podemos alcançar a excelência.", author: "Vince Lombardi" },
  { day: 364, quote: "Eu não sou um produto das minhas circunstâncias. Eu sou um produto das minhas decisões.", author: "Stephen Covey" },
  { day: 365, quote: "O futuro pertence àqueles que acreditam na beleza de seus sonhos.", author: "Eleanor Roosevelt" }
];

/**
 * Retorna a frase motivacional do dia baseada no dia do ano (1-365)
 * @returns FinancialQuote objeto contendo day, quote e author
 */
export function getQuoteOfTheDay(): FinancialQuote {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  
  // Garante que o dia esteja entre 1 e 365
  const normalizedDay = ((dayOfYear - 1) % 365) + 1;
  
  // Encontra a frase correspondente ao dia
  const quote = financialQuotes.find(q => q.day === normalizedDay);
  
  // Retorna a frase encontrada ou a primeira como fallback
  return quote || financialQuotes[0];
}

/**
 * Retorna uma frase aleatória do array
 * @returns FinancialQuote objeto contendo day, quote e author
 */
export function getRandomQuote(): FinancialQuote {
  const randomIndex = Math.floor(Math.random() * financialQuotes.length);
  return financialQuotes[randomIndex];
}

/**
 * Retorna uma frase específica pelo número do dia
 * @param day - Número do dia (1-365)
 * @returns FinancialQuote objeto contendo day, quote e author ou undefined se não encontrado
 */
export function getQuoteByDay(day: number): FinancialQuote | undefined {
  return financialQuotes.find(q => q.day === day);
}
